name = "nexperts-store"
account_id = "7734c5cd2d95cefceaf195b1c610f195"
main = ".open-next/worker.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_PROXY_TARGET = "https://nexperts-ecommerce-api.onrender.com"

[observability]
enabled = true

[triggers]
crons = ["*/2 * * * *"]
